name: Pipeline de Build e Testes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Executar build da aplicação
        run: npm run build

      - name: Salvar artefato de build
        uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: dist/

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Baixar artefato gerado no Build
        uses: actions/download-artifact@v4
        with:
          name: site-dist
          path: dist/

      - name: Executar testes automatizados
        run: npm test
