name: Pipeline de Artefatos e Deploy

on:
  push:
    branches: [ main ]

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Gerar artefato final
        run: npm run build

      - name: Empacotar e versionar artefato
        uses: actions/upload-artifact@v4
        with:
          name: site-package
          path: dist/

  deploy:
    name: Deploy
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Gerar build para publicação
        run: npm run build

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
